// <auto-generated />
using System;
using Infrastructure.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.EntityFramework.Migrations
{
    [DbContext(typeof(VectorMemoryDbContext))]
    partial class VectorMemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.MemoryFragmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("ContentLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int?>("EmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_MemoryFragments_Category");

                    b.HasIndex("CollectionName")
                        .HasDatabaseName("IX_MemoryFragments_CollectionName");

                    b.HasIndex("ContentLength")
                        .HasDatabaseName("IX_MemoryFragments_ContentLength");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MemoryFragments_CreatedAt");

                    b.ToTable("MemoryFragments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
