using Services;

namespace MemoryLibrary;

public class Gloomhaven : ILlmMemory
{
    private List<string> Memory = 
        [
        "Here are Gloomhaven information that the user might ask about. Only answer gloomhaven questions",
        " Gloomhaven is a cooperative game of battling monsters and advancing a player’s own individual goals. The \r\ngame is meant to be played as part of a campaign, where a group of players will use the accompanying Scenario \r\nBook to string together a series of adventures, unlocking new content for the game as they progress. Any \r\nrevealed scenario, however, can also function as a highly variable stand-alone experience"
        ," Play Overview pp.4–12\r\n 1. Character Mats p.6\r\n 2. Character Ability Cards p.7\r\n 3. Item Cards p.8\r\n 4. Monster Statistic Cards p.9\r\n 5. Monster Ability Cards p.10\r\n 6. Battle Goal Cards p.10\r\n 7. \r\nAttack Modifier Cards p.11 \r\nScenario Setup pp.12–16\r\n c. Monster Movement pp.30–31\r\n i. \r\nMonster Interaction with Traps \r\nand Hazardous Terrain p.31\r\n d. Monster Attacks p.31\r\n e. Other Monster Abilities pp.31–32\r\n f. \r\n1. Scenario Page pp.12–13 \r\n2. Overlay Tiles pp.14–15\r\n 3. Scenario Level p.15\r\n 4. Game Variant: Open Information and \r\nSolo Play p.16 \r\nRound Overview pp.16–31\r\n 1. Card Selection pp.16–17\r\n a. Resting p.17\r\n 2. Determining Initiative p.18\r\n 3. Character Turn pp.18–28\r\n a. Move p.19\r\n i. \r\nAmbiguity p.32\r\n g. Bosses p.32\r\n 5. End of Round p.32\r\n a. Round Tracker p.33 \r\nFinishing a Scenario p.33\r\n Special Scenario Rules p.34\r\n Campaign Overview pp.34–40\r\n 1. Campaign Board p.35\r\n 2. Party Sheet p.36\r\n 3. Character Sheet p.37\r\n 4. Personal Quest Cards p.38\r\n 5. Random Item Design Cards p.38\r\n 6. Random Side Scenario Cards p.38\r\n 7. \r\nRevealing a Room p.19\r\n b. Attack pp.19–22\r\n i. \r\nAdvantage and \r\nDisadvantage pp.20–21\r\n ii. \r\niii. \r\nArea Effects p.21\r\n Attack Effects p.22\r\n c. Conditions pp.22–23\r\n d. Elemental Infusions pp.23–24\r\n e. Active Bonuses pp.25–26\r\n i. \r\nShield p.25\r\n ii. \r\nf. \r\nRetaliate p.26\r\n Loot p.27\r\n j. \r\nHeal p.26\r\n g. Summon p.26\r\n h. Recover and Refresh p.27\r\n i. \r\ni. \r\nEnd of Turn Looting p.27\r\n Gaining Experience pp.27–28\r\n k. Character Damage p.28\r\n l. \r\nExhaustion p.28\r\n m. Items p.28\r\n 4. Monster Turn pp.29–32\r\n a. Order of Action p.29\r\n b. Monster Focus pp.29–30\r\n City and Road Event Cards p.39\r\n 8. Sealed Boxes and Envelopes p.40\r\n 9. Town Records p.40\r\n 10. Achievements p.40 \r\nPlaying a Campaign pp.41–47\r\n 1. Traveling and Road Events pp.41–42\r\n a. Completing Road Events pp.41–42\r\n b. Reputation p.42\r\n 2. Visiting Gloomhaven pp.42–48\r\n a. Creating New Characters p.42\r\n b. Completing City Events p.43\r\n c. Buying and Selling Items p.43\r\n d. Leveling Up pp.44–45\r\n i. \r\nAdditional Perks p.44\r\n ii. \r\niii. \r\nBuilding a Hand  \r\nof Cards p.45\r\n Scenario Scaling p.45\r\n e. Donating to the Sanctuary p.45\r\n f. \r\nEnhancing Ability Cards pp.45–47\r\n g. Announcing Retirement p.48\r\n h. Gloomhaven Prosperity p.48\r\n 3. Scenario Completion p.49\r\n Special Conditions for Opening Envelopes p.49\r\n Game Variant: Reduced Randomness p.49\r\n Game Variant: Permanent Death p.50\r\n Game Variant: Random Dungeon Deck pp.50–51\r\n Credits p.51\r\n Quick Guide p.52 (back cover)"
        ,"A scenario consists of a series of rounds that are played until players either meet the victory conditions of the \r\nscenario or fail the scenario. A round consists of the following steps:\r\n 1. Card selection: Each player will either select two cards from his or her hand to play or declare he or she \r\nis performing a long rest action for the round. \r\n2. Determining initiative: Players reveal their cards for the round, and an ability card for each monster \r\ntype currently in play is also revealed. An initiative order is then determined based on the initiative \r\nvalues of these revealed cards. \r\n3. Character and monster turns: Starting with the lowest initiative, players and monsters will act out their \r\nturns, performing the actions on their cards, possibly modified by character item cards. \r\n4. Cleanup: Some cleanup may be required at the end of the round (see End of Round on p. 32 for details)"
        ,"Players should not show other players the cards in their hands nor give specific information about any \r\nnumerical value or title on any of their cards. They are, however, allowed to make general statements about \r\ntheir actions for the round and discuss strategy.\r\n • Examples of appropriate communication: “I’m attacking this guard near the middle of the round.”; \r\n“I’m planning on moving here and healing you pretty early in the round, hopefully before the monsters \r\nattack.” \r\n• Examples of inappropriate communication: “You’ll need lower than an initiative 17 to go before me.”; \r\n“I should be doing 4 points of damage to the bandit, so you don’t have to worry about him.”; “I’m going \r\nto use Impaling Eruption and wipe out everyone.” "
        ];
    
    public string ExportMemory()
    {
        return string.Join(Environment.NewLine, Memory);
    }

    public void ImportMemory(string section)
    {
        Memory.Add(section);
    }
}
