namespace Entities;

/// <summary>
/// Database entity for storing questions, their answers, and which LLM was used.
/// Maps to the Questions table in MSSQL.
/// </summary>
public class QuestionEntity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    /// <summary>
    /// The question asked by the user
    /// </summary>
    public string Question { get; set; } = string.Empty;
    
    /// <summary>
    /// The answer generated by the LLM
    /// </summary>
    public string Answer { get; set; } = string.Empty;
    
    /// <summary>
    /// Foreign key to the LLM that generated this answer
    /// </summary>
    public Guid LlmId { get; set; }
    
    /// <summary>
    /// Timestamp when the question was asked
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
