<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Application.AI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_cased.txt" />
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_cased_german.txt" />
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_cased_large.txt" />
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_cased_multilingual.txt" />
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_uncased.txt" />
    <Content Remove="C:\Users\belfe\.nuget\packages\berttokenizers\1.2.0\contentFiles\any\net6.0\Vocabularies\base_uncased_large.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Application.AI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\Factories\Factories.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BERTTokenizers" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" Version="2.0.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
  </ItemGroup>

</Project>
