namespace Services.GoalAgent;

/// <summary>
/// Verification state of a single <see cref="GoalRequirement"/> within a goal-agent run.
/// Mirrors the TDD traffic-light idea: a requirement starts unverified ("no test run yet"),
/// is worked on and checked each iteration, and the run only completes when every
/// requirement is <see cref="Passed"/>.
/// </summary>
public enum RequirementStatus
{
    /// <summary>Not yet checked against the workspace (or invalidated by new work).</summary>
    Unverified,

    /// <summary>The agent is currently doing file work to satisfy this requirement.</summary>
    Working,

    /// <summary>The agent is currently checking this requirement against the workspace.</summary>
    Verifying,

    /// <summary>Last verification judged the requirement fulfilled ("green").</summary>
    Passed,

    /// <summary>Last verification judged the requirement not fulfilled ("red");
    /// <see cref="GoalRequirement.LastVerdict"/> holds the reason.</summary>
    Failed
}

/// <summary>
/// One concrete, checkable requirement derived by the LLM from the user's free-text goal
/// description (e.g. "Filen readme.txt finns i arbetsytan"). The goal agent works to satisfy
/// it and then verifies it against the workspace files each iteration.
/// </summary>
public class GoalRequirement
{
    public Guid Id { get; } = Guid.NewGuid();

    /// <summary>The requirement text as generated by the LLM (one "KRAV:" line).</summary>
    public string Description { get; }

    public RequirementStatus Status { get; internal set; } = RequirementStatus.Unverified;

    /// <summary>
    /// Motivation from the most recent verification: the reason a requirement was judged
    /// failed (fed back into the next work prompt, like a failing test message), or null when
    /// the requirement has not been verified yet / passed without remarks.
    /// </summary>
    public string? LastVerdict { get; internal set; }

    public GoalRequirement(string description)
    {
        if (string.IsNullOrWhiteSpace(description))
            throw new ArgumentException("Requirement description cannot be empty.", nameof(description));

        Description = description;
    }
}
