namespace Services.GoalAgent;

/// <summary>
/// Verification state of a single <see cref="GoalRequirement"/> within a goal-agent run.
/// Mirrors the TDD traffic-light idea: a requirement starts unverified ("no test run yet"),
/// is worked on and checked each iteration, and the run only completes when every
/// requirement is <see cref="Passed"/>.
/// </summary>
public enum RequirementStatus
{
    /// <summary>Not yet checked against the workspace (or invalidated by new work).</summary>
    Unverified,

    /// <summary>The agent is currently doing file work to satisfy this requirement.</summary>
    Working,

    /// <summary>The agent is currently checking this requirement against the workspace.</summary>
    Verifying,

    /// <summary>Last verification judged the requirement fulfilled ("green").</summary>
    Passed,

    /// <summary>Last verification judged the requirement not fulfilled ("red");
    /// <see cref="GoalRequirement.LastVerdict"/> holds the reason.</summary>
    Failed
}

/// <summary>
/// One concrete, checkable requirement derived by the LLM from the user's free-text goal
/// description (e.g. "Filen readme.txt finns i arbetsytan"). The goal agent works to satisfy
/// it and then verifies it against the workspace files each iteration.
/// </summary>
public class GoalRequirement
{
    public Guid Id { get; } = Guid.NewGuid();

    /// <summary>The requirement text as generated by the LLM (one "KRAV:" line).</summary>
    public string Description { get; }

    public RequirementStatus Status { get; internal set; } = RequirementStatus.Unverified;

    /// <summary>
    /// Motivation from the most recent verification: the reason a requirement was judged
    /// failed (fed back into the next work prompt, like a failing test message), or null when
    /// the requirement has not been verified yet / passed without remarks.
    /// </summary>
    public string? LastVerdict { get; internal set; }

    /// <summary>
    /// True when the most recent verification reply could not be interpreted as a
    /// GODKÄNT/UNDERKÄNT verdict at all (empty reply, leaked template tokens, ...). The
    /// requirement still counts as failed — never green by accident — but there is no real
    /// defect to act on: <see cref="LastVerdict"/> holds a diagnostic for the UI, not a
    /// motivation, so it must not be fed into the next work prompt, and no file work should be
    /// attempted for the requirement until a verification produces a readable verdict. (In a
    /// real run, "fixing" a parse hiccup led the model to rewrite a perfectly fine file.)
    /// </summary>
    public bool VerdictInconclusive { get; internal set; }

    /// <summary>
    /// Fingerprint (name + size + last-write time) of the workspace files this requirement talks
    /// about, taken when it last passed verification. While it still matches, re-verifying can
    /// only produce the same verdict, so the check is skipped — the single largest source of
    /// wasted LLM calls in a long run, since every iteration re-verifies the whole suite.
    /// Null whenever the requirement is not currently passed.
    /// </summary>
    internal string? VerifiedFingerprint { get; set; }

    /// <summary>
    /// How many verifications in a row have failed this requirement for the same reason. Used to
    /// notice that the loop is stuck: identical verdict after identical verdict means the work
    /// steps are not moving the needle, and iterating further just burns time.
    /// </summary>
    public int RepeatedFailureCount { get; internal set; }

    /// <summary>
    /// Normalised form of the verdict behind <see cref="RepeatedFailureCount"/>, used to tell
    /// "failed again for the same reason" from "failed for a new reason" (which resets the count).
    /// </summary>
    internal string? LastVerdictKey { get; set; }

    public GoalRequirement(string description)
    {
        if (string.IsNullOrWhiteSpace(description))
            throw new ArgumentException("Requirement description cannot be empty.", nameof(description));

        Description = description;
    }
}
